[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rust_backend = "4HGr5zRPPn6SHLX5E3oBsu5WU77htwvzU4Bqs1PYTS9q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
